package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSocialComment;
import org.linlinjava.litemall.db.domain.LitemallSocialCommentExample;

public interface LitemallSocialCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    long countByExample(LitemallSocialCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSocialCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int insert(LitemallSocialComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSocialComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    LitemallSocialComment selectOneByExample(LitemallSocialCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    LitemallSocialComment selectOneByExampleSelective(@Param("example") LitemallSocialCommentExample example, @Param("selective") LitemallSocialComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    LitemallSocialComment selectOneByExampleWithBLOBs(LitemallSocialCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    List<LitemallSocialComment> selectByExampleSelective(@Param("example") LitemallSocialCommentExample example, @Param("selective") LitemallSocialComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    List<LitemallSocialComment> selectByExampleWithBLOBs(LitemallSocialCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    List<LitemallSocialComment> selectByExample(LitemallSocialCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    LitemallSocialComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSocialComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    LitemallSocialComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    LitemallSocialComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSocialComment record, @Param("example") LitemallSocialCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallSocialComment record, @Param("example") LitemallSocialCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSocialComment record, @Param("example") LitemallSocialCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSocialComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallSocialComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSocialComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallSocialCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}