package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSocialTopic;
import org.linlinjava.litemall.db.domain.LitemallSocialTopicExample;

public interface LitemallSocialTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    long countByExample(LitemallSocialTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSocialTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    int insert(LitemallSocialTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSocialTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    LitemallSocialTopic selectOneByExample(LitemallSocialTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    LitemallSocialTopic selectOneByExampleSelective(@Param("example") LitemallSocialTopicExample example, @Param("selective") LitemallSocialTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    List<LitemallSocialTopic> selectByExampleSelective(@Param("example") LitemallSocialTopicExample example, @Param("selective") LitemallSocialTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    List<LitemallSocialTopic> selectByExample(LitemallSocialTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    LitemallSocialTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSocialTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    LitemallSocialTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    LitemallSocialTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSocialTopic record, @Param("example") LitemallSocialTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSocialTopic record, @Param("example") LitemallSocialTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSocialTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSocialTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallSocialTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}