package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallSocialDynamic;
import org.linlinjava.litemall.db.domain.LitemallSocialDynamicExample;

public interface LitemallSocialDynamicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    long countByExample(LitemallSocialDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallSocialDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int insert(LitemallSocialDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int insertSelective(LitemallSocialDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    LitemallSocialDynamic selectOneByExample(LitemallSocialDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    LitemallSocialDynamic selectOneByExampleSelective(@Param("example") LitemallSocialDynamicExample example, @Param("selective") LitemallSocialDynamic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    LitemallSocialDynamic selectOneByExampleWithBLOBs(LitemallSocialDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    List<LitemallSocialDynamic> selectByExampleSelective(@Param("example") LitemallSocialDynamicExample example, @Param("selective") LitemallSocialDynamic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    List<LitemallSocialDynamic> selectByExampleWithBLOBs(LitemallSocialDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    List<LitemallSocialDynamic> selectByExample(LitemallSocialDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    LitemallSocialDynamic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallSocialDynamic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    LitemallSocialDynamic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    LitemallSocialDynamic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallSocialDynamic record, @Param("example") LitemallSocialDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallSocialDynamic record, @Param("example") LitemallSocialDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallSocialDynamic record, @Param("example") LitemallSocialDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallSocialDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallSocialDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallSocialDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallSocialDynamicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_social_dynamic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}