package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserFollow;
import org.linlinjava.litemall.db.domain.LitemallUserFollowExample;

public interface LitemallUserFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    int insert(LitemallUserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    LitemallUserFollow selectOneByExample(LitemallUserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    LitemallUserFollow selectOneByExampleSelective(@Param("example") LitemallUserFollowExample example, @Param("selective") LitemallUserFollow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    List<LitemallUserFollow> selectByExampleSelective(@Param("example") LitemallUserFollowExample example, @Param("selective") LitemallUserFollow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    List<LitemallUserFollow> selectByExample(LitemallUserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    LitemallUserFollow selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserFollow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    LitemallUserFollow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    LitemallUserFollow selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserFollow record, @Param("example") LitemallUserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserFollow record, @Param("example") LitemallUserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallUserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_follow
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}